### ISSUE TITLE
Support Lisp vectors as MAC addresses

### ISSUE THREAD

**Issue by phoe** [dnaeon/cl-wol#1]
https://github.com/dnaeon/cl-wol/blob/d09d46124023f88ccb580209d8f17451c2bc09e5/README.org#L38-L43

Programmatic users of `cl-wol` might want to avoid converting MAC addresses (which are generally of type `(vector (unsigned-byte 8) (6))`) to strings in order to use this library. That's because `cl-wol` uses strings as the internal representation of MAC addresses; would it be better to switch to ub8 vectors and to specify methods (and write tests) to ensure that both strings and vectors are acceptable as MAC addresses in the Lisp API?

**Comment by dnaeon** [comment]
Hey @phoe ,

Makes total sense. I'll make sure to have this one implemented.

Thanks!

**Comment by dnaeon** [comment]
@phoe , can you please check out the https://github.com/dnaeon/cl-wol/tree/issue/1 branch, which provides support for making magic packets using ub8 vectors and let me know how it looks?

If things look good I'll go ahead and merge it.

**Comment by phoe** [comment]
Done - reviewed in #2.

**Comment by dnaeon** [comment]
Thanks, @phoe !
